Updated the Contract WebaverseERC721
webaverse/drop-contracts pull request #5
Opened 2021-11-28 12:46 UTC by mohsinanees

I have updated the smart contract WebaverseERC721 with the following changes:

1- Added `mintBatch` function that could allow us to mint tokens in bulk.
2- Resolved the token URI issues in the previous one by adding the check for the provided URI in the mint function.
3- Redeployed the contract on rinkeby and updated the ABI and config on redis.
4- Added events URI, Claim, ExternalClaim to enhance the speed and efficiency of fetching the data from the smart contract on the redis-server and api-backend.

2021-11-28 20:41 UTC, avaer reviewed
Why is fs in package.json? That is a native module.

2021-11-28 20:42 UTC, avaer reviewed
Should not put your own dev machine directory names into the configs…

2021-11-28 20:43 UTC, avaer requested changes
Very messy code needs cleanup, but largely ok.

2021-11-28 20:44 UTC, avaer commented
Why is hardhat labeled a type of network in the configs?

2021-11-28 20:45 UTC, avaer commented
Why is the etherscan api key leaked?

2021-11-28 20:50 UTC, abeersaqib commented on tsconfig.json
> +    "rootDir": "/home/mohsin/Desktop/Webaverse-repos/drop-contracts",                               /* Specify the root directory of input files. Use to control the output directory structure with --
@mohsinanees Please resolve this

2021-11-29 12:46 UTC, mohsinanees commented
> Why is hardhat labeled a type of network in the configs?

It is labeled as a network because hardhat runs its own virtual VM to run the tests just like the ganache-cli.

2021-12-15 07:00 UTC, avaer approved these changes

2021-12-15 07:00 UTC, merged